use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "kebab-case")]
pub enum AgentModeKind {
    SafeChat,
    CodingAssistant,
    PlanOnly,
    ActMode,
    CodeReviewer,
    SecurityAuditor,
    UiUxDesigner,
    DocsWriter,
    TestRunner,
    BrowserQa,
    GithubPrAssistant,
    AutomationBuilder,
    Researcher,
    VoiceCompanionPreview,
    Custom(String),
}

impl Default for AgentModeKind {
    fn default() -> Self {
        AgentModeKind::CodingAssistant
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct AgentModeProfile {
    pub name: String,
    pub kind: AgentModeKind,
    pub description: String,
    pub default_model: Option<String>,
    pub system_prompt_extension: Option<String>,
    pub tools_allowed: Vec<String>,
    pub skills_preferred: Vec<String>,
    pub recipes_allowed: Vec<String>,
    pub browser_allowed: bool,
    pub transports_allowed: bool,
    pub risk_tolerance: crate::approval::RiskLevel,
}

impl AgentModeProfile {
    pub fn get_builtins() -> Vec<Self> {
        vec![
            Self {
                name: "Safe Chat".into(),
                kind: AgentModeKind::SafeChat,
                description: "Conversational mode with no dangerous actions allowed.".into(),
                default_model: Some("balanced".into()),
                system_prompt_extension: Some("You are a helpful chat assistant. You cannot modify files or run commands.".into()),
                tools_allowed: vec![], // None
                skills_preferred: vec![],
                recipes_allowed: vec![],
                browser_allowed: false,
                transports_allowed: false,
                risk_tolerance: crate::approval::RiskLevel::Low,
            },
            Self {
                name: "Coding Assistant".into(),
                kind: AgentModeKind::CodingAssistant,
                description: "Standard pair programming mode with file writes and safe commands.".into(),
                default_model: Some("balanced".into()),
                system_prompt_extension: Some("You are a helpful coding assistant.".into()),
                tools_allowed: vec!["*".into()],
                skills_preferred: vec![],
                recipes_allowed: vec!["*".into()],
                browser_allowed: true,
                transports_allowed: false,
                risk_tolerance: crate::approval::RiskLevel::Medium,
            },
            Self {
                name: "Plan Only".into(),
                kind: AgentModeKind::PlanOnly,
                description: "Only plans changes, no execution.".into(),
                default_model: Some("reasoning".into()),
                system_prompt_extension: Some("Create detailed plans but do not execute them.".into()),
                tools_allowed: vec!["view_file".into(), "grep_search".into(), "list_dir".into()],
                skills_preferred: vec!["architecture-review".into()],
                recipes_allowed: vec![],
                browser_allowed: true,
                transports_allowed: false,
                risk_tolerance: crate::approval::RiskLevel::Low,
            },
            Self {
                name: "Act Mode".into(),
                kind: AgentModeKind::ActMode,
                description: "Autonomous execution mode for trusted tasks.".into(),
                default_model: Some("capable".into()),
                system_prompt_extension: Some("Execute the requested tasks efficiently.".into()),
                tools_allowed: vec!["*".into()],
                skills_preferred: vec![],
                recipes_allowed: vec!["*".into()],
                browser_allowed: true,
                transports_allowed: false,
                risk_tolerance: crate::approval::RiskLevel::High,
            },
            Self {
                name: "Code Reviewer".into(),
                kind: AgentModeKind::CodeReviewer,
                description: "Reviews code for quality and bugs.".into(),
                default_model: Some("balanced".into()),
                system_prompt_extension: Some("You are a strict code reviewer. Point out issues and suggest improvements.".into()),
                tools_allowed: vec!["view_file".into(), "grep_search".into(), "list_dir".into(), "github_pr_review".into()],
                skills_preferred: vec!["Security Audit Pack".into(), "Testing Pack".into()],
                recipes_allowed: vec!["github-pr-review".into()],
                browser_allowed: false,
                transports_allowed: false,
                risk_tolerance: crate::approval::RiskLevel::Low,
            },
            Self {
                name: "Security Auditor".into(),
                kind: AgentModeKind::SecurityAuditor,
                description: "Deep security analysis of the codebase.".into(),
                default_model: Some("reasoning".into()),
                system_prompt_extension: Some("Look for security vulnerabilities, secrets, and insecure patterns.".into()),
                tools_allowed: vec!["view_file".into(), "grep_search".into(), "list_dir".into()],
                skills_preferred: vec!["Security Audit Pack".into()],
                recipes_allowed: vec![],
                browser_allowed: false,
                transports_allowed: false,
                risk_tolerance: crate::approval::RiskLevel::Low,
            },
            Self {
                name: "UI/UX Designer".into(),
                kind: AgentModeKind::UiUxDesigner,
                description: "Focus on frontend aesthetics and user experience.".into(),
                default_model: Some("capable".into()),
                system_prompt_extension: Some("Focus heavily on premium UI/UX design, stunning visuals, and smooth animations.".into()),
                tools_allowed: vec!["*".into()],
                skills_preferred: vec!["antigravity-master-ui".into(), "avant-garde-ui-ux".into()],
                recipes_allowed: vec!["*".into()],
                browser_allowed: true,
                transports_allowed: false,
                risk_tolerance: crate::approval::RiskLevel::Medium,
            },
            Self {
                name: "Docs Writer".into(),
                kind: AgentModeKind::DocsWriter,
                description: "Writes and updates documentation.".into(),
                default_model: Some("balanced".into()),
                system_prompt_extension: Some("Write clear, concise, and accurate documentation.".into()),
                tools_allowed: vec!["view_file".into(), "grep_search".into(), "list_dir".into(), "write_file".into(), "replace_file_content".into()],
                skills_preferred: vec![],
                recipes_allowed: vec![],
                browser_allowed: true,
                transports_allowed: false,
                risk_tolerance: crate::approval::RiskLevel::Low,
            },
            Self {
                name: "Test Runner".into(),
                kind: AgentModeKind::TestRunner,
                description: "Focuses on writing and running tests.".into(),
                default_model: Some("balanced".into()),
                system_prompt_extension: Some("Write robust tests and run test suites.".into()),
                tools_allowed: vec!["*".into()],
                skills_preferred: vec!["Testing Pack".into()],
                recipes_allowed: vec!["cargo-check-on-save".into()],
                browser_allowed: false,
                transports_allowed: false,
                risk_tolerance: crate::approval::RiskLevel::Medium,
            },
            Self {
                name: "Browser QA".into(),
                kind: AgentModeKind::BrowserQa,
                description: "Visual and functional testing in the browser.".into(),
                default_model: Some("capable".into()),
                system_prompt_extension: Some("Test applications in the browser using the browser adapter.".into()),
                tools_allowed: vec!["browser_open".into(), "browser_screenshot".into(), "browser_read".into(), "browser_qa".into()],
                skills_preferred: vec!["frontend visual review".into()],
                recipes_allowed: vec!["browser-qa".into()],
                browser_allowed: true,
                transports_allowed: false,
                risk_tolerance: crate::approval::RiskLevel::Medium,
            },
            Self {
                name: "GitHub PR Assistant".into(),
                kind: AgentModeKind::GithubPrAssistant,
                description: "Manages GitHub issues, branches, and PRs.".into(),
                default_model: Some("balanced".into()),
                system_prompt_extension: Some("You assist with GitHub workflow operations.".into()),
                tools_allowed: vec!["github_*".into()],
                skills_preferred: vec![],
                recipes_allowed: vec!["github-pr-review".into()],
                browser_allowed: false,
                transports_allowed: false,
                risk_tolerance: crate::approval::RiskLevel::Medium,
            },
            Self {
                name: "Automation Builder".into(),
                kind: AgentModeKind::AutomationBuilder,
                description: "Creates scripts and recipes for automation.".into(),
                default_model: Some("capable".into()),
                system_prompt_extension: Some("Build reliable automation scripts and CI/CD pipelines.".into()),
                tools_allowed: vec!["*".into()],
                skills_preferred: vec![],
                recipes_allowed: vec!["*".into()],
                browser_allowed: false,
                transports_allowed: false,
                risk_tolerance: crate::approval::RiskLevel::High,
            },
            Self {
                name: "Researcher".into(),
                kind: AgentModeKind::Researcher,
                description: "Deep research into topics or codebases.".into(),
                default_model: Some("reasoning".into()),
                system_prompt_extension: Some("Conduct thorough research and present detailed findings.".into()),
                tools_allowed: vec!["view_file".into(), "grep_search".into(), "list_dir".into(), "browser_open".into(), "browser_read".into()],
                skills_preferred: vec![],
                recipes_allowed: vec![],
                browser_allowed: true,
                transports_allowed: false,
                risk_tolerance: crate::approval::RiskLevel::Low,
            },
            Self {
                name: "Voice Companion Preview".into(),
                kind: AgentModeKind::VoiceCompanionPreview,
                description: "A friendly conversational voice companion.".into(),
                default_model: Some("fast".into()),
                system_prompt_extension: Some("You are a friendly voice companion. Keep responses concise for speech.".into()),
                tools_allowed: vec![],
                skills_preferred: vec![],
                recipes_allowed: vec![],
                browser_allowed: false,
                transports_allowed: true,
                risk_tolerance: crate::approval::RiskLevel::Low,
            },
        ]
    }
}
